### ISSUE TITLE
Milestone 2 Todo List 

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/dsci-532_group_02#17]
Repo:
- [x] 1. Files & folders organization (e.g. Proposal.md -> doc/, Proposal.Rmd -> reports/)

```
project/
├── data/            .csv .hdf .pkl .feather
│   ├── processed/
│   └── raw/
├── src/             .py .R
├── reports/         .ipynb .Rmd
├── doc/             .md
├── environment.yaml (or/and requirements.txt)
├── README.md
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
└── LICENSE.md
```

- [x] 2. app.py (in root)
- [x] 3. requirements.txt (in root)
- [x] 4. reflection-milestone2.md (in doc/)

README (README.md)
- [x] 5. link to our deployed dashboard on Heroku (must)
- [x] (6.) improvement (optional)

Canvas Submission
- [x] 7. canvas-submission.html (Release)

Link to the milestone 2 requirement:
https://github.ubc.ca/MDS-2020-21/DSCI_532_viz-2_students/blob/master/release/milestone2/milestone2.md

**Comment by elabandari** [comment]
Overview of Allocation of Tasks and Meetings:

1. app.py:
- [x] Histogram 1 -> Ela 
- [x] Histogram 2 -> Elina 
- [x] Top 5/HSV controls -> Rachel 
- [x] HSV top 5 color cards -> Lu 


2. Reflection: 
- [x] Histogram 1 -> Ela 
- [x] Histogram 2 -> Elina 
- [x] Most similar colours -> Rachel + Lu 


3. Meetings:
- [x] Wednesday at 8:45 AM (Stand-up/Check-in)
- [x] Friday at 2:00 PM (Deploy on Heroku + requirements.txt)

**Comment by rainbowxyt0305** [comment]
Done all action items.
