### ISSUE TITLE
Milestone 1 Todo List

### ISSUE THREAD

**Issue by KangboLu** [UBC-MDS/dsci-532_group_02#2]
Repo Setup:
- [x] 1. Make Github Repo
- [x] 2. File organizations
- [x] 3. Team Contract (root directory, team-contract.md)
- [x] 4. Code of Conduct (root directory, CODE_OF_CONDUCT.md) 
- [x] 5. Contribution guidelines (root directory, CONTRIBUTING.md)

Proposal (proposal.md)
- [x] 6.0. Section 0: [Proposal discussion](https://github.com/UBC-MDS/dsci-532_group_02/issues/3)
- [x] 6.1. Section 1: Motivation & Purpose
- [x] 6.2. Section 2: Description of the data
- [x] 6.3. Section 3: [Research Questions](https://github.com/UBC-MDS/dsci-532_group_02/issues/7) & usage scenarios 

README
- [x] 7. Description of app & sketch (README.md)

Link to the milestone 1 requirement: https://github.ubc.ca/MDS-2020-21/DSCI_532_viz-2_students/blob/master/release/milestone1/milestone1.md

**Comment by rainbowxyt0305** [comment]
Repo Setup:
- [x] 1. Make Github Repo
- [x] 2. File organizations
- [x] 3. Team Contract (part of canvas-submission.md)
- [x] 4. Code of Conduct (root directory, CODE_OF_CONDUCT.md) 
- [x] 5. Contribution guidelines (root directory, CONTRIBUTING.md)

Proposal (proposal.md)
- [x] 6.0. Section 0: [Proposal discussion](https://github.com/UBC-MDS/dsci-532_group_02/issues/3)
- [x] 6.1. Section 1: Motivation & Purpose
- [x] 6.2. Section 2: Description of the data
- [x] 6.3. Section 3: Research Questions & usage scenarios

README (README.md)
- [x] 7. Description of app & sketch (README.md)

Canvas Submission
- [x] 8. canvas-submission.md (include both Release & Team Contract)

Link to the milestone 1 requirement: 
https://github.ubc.ca/MDS-2020-21/DSCI_532_viz-2_students/blob/master/release/milestone1/milestone1.md
