### ISSUE TITLE
Milestone 4 Tasks

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/dsci-532_group_02#30]
Repo:  
- [x] 1. Update About to include description, app link, keywords

app.py
- [x] 2. set title
- [x] 3. take away debug=True
- [x] 4. Refine histograms with plotly  
- [x] 5. Address TA feedback from Milestone 2 & 3 & Peer Feedbacks

Deployment on Heroku:
- [x] 6. setup Heroku's GitHub integration to automate our deploys

Reflection (in doc/reflection-milestone4.md):
- [x] 7. Reflection (Why did we choose to go with Python or R)

Document docstrings (Optional):
- [x] 8. write functions' docstrings

Auto-deployed Heroku PR (Optional)
- [x] 9. include auto-deployed Heroku PR

Canvas Submission:
- [x] 10. `canvas-submission.html` (include link to auto-deployed Heroku PR)

**Comment by KangboLu** [comment]
point 2 and 6 are completed
![image](https://user-images.githubusercontent.com/17485959/106527681-8856d580-649c-11eb-840f-04b4318c448b.png)
![image](https://user-images.githubusercontent.com/17485959/106527718-91e03d80-649c-11eb-9470-63a129187089.png)

**Comment by rainbowxyt0305** [comment]
Done all action items.

**Comment by rainbowxyt0305** [comment]
Done all action items.
