### ISSUE TITLE
Milestone 4 Todo List

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/dsci-532_group_02#31]
- [x] 1. Github issues: TA's feedback & Peer feedback (Elina)

- [x] 2. Playing around with histograms: overlaying historgrams, density, & outline aesthetic (Ela)

- [x] 3. reflection-milestone4.md (Ela, Rachel)

- [x] 4. Docstrings (Ela, Elina, Lu)

- [x] 5. canvas-submission.html: Release & Auto-deployed Heroku PR (Rachel)

Link to the milestone 4 requirement:
https://github.ubc.ca/MDS-2020-21/DSCI_532_viz-2_students/blob/master/release/milestone4/milestone4.md

**Comment by rainbowxyt0305** [comment]
Done all action items.
