### ISSUE TITLE
Milestone 1 Meeting Minutes & Action Items

### ISSUE THREAD

**Issue by rainbowxyt0305** [UBC-MDS/dsci-532_group_02#4]
Please see all Milestone 1 Group Meeting Minutes commented below.

**Comment by rainbowxyt0305** [comment]
When: Monday 2021-01-11 532 L01

Topic:
- Introduction
- Team Contract construction
- Topic & Dataset brief discussion

Action Items:
- [x] Research on dataset and topic by 7pm the same day
- [x] Share and vote for the most interesting dataset and topic during the 7pm meeting
- [x] Task allocation for the week

**Comment by rainbowxyt0305** [comment]
When: Monday 2021-01-11 7PM

Topic:
- Topic & Dataset discussion & voting
- Task allocation

Action Items:
- [x] EVERYONE: Come up with good Research Questions on selected topic and dataset 
- [x] RACHEL:  proposal.md [Section 1: Motivation & Purpose & Section 2: Description of the data]
- [x] ELINA: proposal.md [Section 3: Research Questions & usage scenarios]
- [x] LU: README.md [Description of app]
- [x] ELA: README.md [Sketch]
